package net.serlith.purpur.data;

import de.bsommerfeld.jshepherd.annotation.Comment;
import de.bsommerfeld.jshepherd.annotation.Key;
import de.bsommerfeld.jshepherd.core.ConfigurablePojo;
import de.bsommerfeld.jshepherd.core.ConfigurationLoader;
import net.serlith.purpur.PurpurBars;
import org.jspecify.annotations.NullMarked;

import java.util.Collection;
import java.util.List;
import java.util.UUID;

@NullMarked
@Comment({
        "DO NOT EDIT THIS FILE MANUALLY"
})
@SuppressWarnings({"FieldMayBeFinal"})
public class DataStorage extends ConfigurablePojo<DataStorage> {
    private DataStorage() {
    }

    @SuppressWarnings("NullAway.Init")
    private static DataStorage INSTANCE;
    public static DataStorage getInstance() {
        return INSTANCE;
    }

    private static boolean INITIALIZED = false;
    public static void initialize(final PurpurBars plugin) {
        if (INITIALIZED) {
            return;
        }

        INSTANCE = ConfigurationLoader.from(plugin.getStorageFolder().resolve("data.yml"))
                .withComments()
                .load(DataStorage::new);
        INSTANCE.save();
        INITIALIZED = true;
    }

    @Key("ram-bar")
    private List<String> ramBarStrings = List.of();

    @Key("tps-bar")
    private List<String> tpsBarStrings = List.of();

    @Key("compass-bar")
    private List<String> compassBarStrings = List.of();

    @Key("world-follow-bar")
    private List<String> worldFollowBarStrings = List.of();

    @Key("region-follow-bar")
    private List<String> regionFollowBarStrings = List.of();

    public List<UUID> getRamBar() {
        return this.ramBarStrings.stream().map(UUID::fromString).toList();
    }

    public List<UUID> getTpsBar() {
        return this.tpsBarStrings.stream().map(UUID::fromString).toList();
    }

    public List<UUID> getCompassBar() {
        return this.compassBarStrings.stream().map(UUID::fromString).toList();
    }

    public List<UUID> getWorldFollowBar() {
        return this.worldFollowBarStrings.stream().map(UUID::fromString).toList();
    }

    public List<UUID> getRegionFollowBar() {
        return this.regionFollowBarStrings.stream().map(UUID::fromString).toList();
    }

    public void setRamBar(final Collection<UUID> bars) {
        this.ramBarStrings = bars.stream().map(Object::toString).toList();
    }

    public void setTpsBar(final Collection<UUID> bars) {
        this.tpsBarStrings = bars.stream().map(Object::toString).toList();
    }

    public void setCompassBar(final Collection<UUID> bars) {
        this.compassBarStrings = bars.stream().map(Object::toString).toList();
    }

    public void setWorldFollowBar(final Collection<UUID> bars) {
        this.worldFollowBarStrings = bars.stream().map(Object::toString).toList();
    }

    public void setRegionFollowBar(final Collection<UUID> bars) {
        this.regionFollowBarStrings = bars.stream().map(Object::toString).toList();
    }

}
