package net.serlith.purpur.data;

import net.j4c0b3y.api.config.StaticConfig;
import net.serlith.purpur.PurpurBars;

import java.io.File;
import java.util.Set;
import java.util.UUID;

@StaticConfig.Header({
        "DO NOT EDIT THIS FILE MANUALLY"
})
public class DataStorage extends StaticConfig {

    @Ignore
    public static DataStorage INSTANCE;

    public DataStorage(PurpurBars plugin) {
        super(new File(plugin.getStorageFolder(), "data.yml"), plugin.getConfigHandler());
        INSTANCE = this;
    }

    public static Set<UUID> RAM_BAR = Set.of();

    public static Set<UUID> TPS_BAR = Set.of();

    public static Set<UUID> COMPASS_BAR = Set.of();

}
