package net.serlith.purpur.data;

import de.bsommerfeld.jshepherd.annotation.Comment;
import de.bsommerfeld.jshepherd.annotation.Key;
import de.bsommerfeld.jshepherd.core.ConfigurablePojo;
import de.bsommerfeld.jshepherd.core.ConfigurationLoader;
import net.serlith.purpur.PurpurBars;
import org.jspecify.annotations.NullMarked;

import java.util.Set;
import java.util.UUID;

@NullMarked
@Comment({
        "DO NOT EDIT THIS FILE MANUALLY"
})
public class DataStorage extends ConfigurablePojo<DataStorage> {
    private DataStorage() {
    }

    @SuppressWarnings("NullAway.Init")
    private static DataStorage INSTANCE;
    public static DataStorage getInstance() {
        return INSTANCE;
    }

    private static boolean INITIALIZED = false;
    public static void initialize(final PurpurBars plugin) {
        if (INITIALIZED) {
            return;
        }

        INSTANCE = ConfigurationLoader.from(plugin.getStorageFolder().resolve("data.yml"))
                .withComments()
                .load(DataStorage::new);
        INSTANCE.save();
        INITIALIZED = true;
    }

    @Key("ram-bar")
    public Set<UUID> ramBar = Set.of();

    @Key("tps-bar")
    public Set<UUID> tpsBar = Set.of();

    @Key("compass-bar")
    public Set<UUID> compassBar = Set.of();

    @Key("world-follow-bar")
    public Set<UUID> worldFollowBar = Set.of();

    @Key("region-follow-bar")
    public Set<UUID> regionFollowBar = Set.of();

}
