name: PurpurBars
version: $version
main: net.serlith.purpur.PurpurBars
api-version: '1.21'
authors: [ Biquaternions ]
description: Plugin implementation of Purpur's tps and ram bars
website: https://serlith.net
folia-supported: true
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
