name: PurpurBars
version: $version
main: net.serlith.purpur.PurpurBars
api-version: "1.13"
author: Biquaternions
description: Plugin implementation of Purpur's tps and ram bars
website: https://serlith.net
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.0
  - org.jetbrains:annotations:26.0.1
  - net.kyori:adventure-text-minimessage:4.18.0