
#
# Formatting that will be used by the bars
# These configurations only support Adventure's MiniMessage
# Learn more: https://docs.advntr.dev/minimessage/format.html
#
format:
  # TpsBar format configuration
  tpsbar:
    title: "<gray>TPS<yellow>:</yellow> <tps> MSPT<yellow>:</yellow> <mspt> Ping<yellow>:</yellow> <ping>ms"
    # Possible overlays: https://jd.advntr.dev/api/4.7.0/net/kyori/adventure/bossbar/BossBar.Overlay.html
    progress_overlay: "NOTCHED_20"
    # Possible values: TPS, MSPT & PING
    progress_fill_mode: "MSPT"
    # Possible colors: https://jd.advntr.dev/api/4.7.0/net/kyori/adventure/bossbar/BossBar.Color.html
    progress_color:
      good: "GREEN"
      medium: "YELLOW"
      low: "RED"
    text_color:
      good: "<gradient:#55ff55:#00aa00><text></gradient>"
      medium: "<gradient:#ffff55:#ffaa00><text></gradient>"
      low: "<gradient:#ff5555:#aa0000><text></gradient>"
    # Delay (in ticks) between bar update
    tick_interval: 20

  # RamBar format configuration
  rambar:
    title: "<gray>Ram<yellow>:</yellow> <used>/<xmx> (<percent>)"
    # Possible overlays: https://jd.advntr.dev/api/4.7.0/net/kyori/adventure/bossbar/BossBar.Overlay.html
    progress_overlay: "NOTCHED_20"
    # Possible colors: https://jd.advntr.dev/api/4.7.0/net/kyori/adventure/bossbar/BossBar.Color.html
    progress_color:
      good: "GREEN"
      medium: "YELLOW"
      low: "RED"
    text_color:
      good: "<gradient:#55ff55:#00aa00><text></gradient>"
      medium: "<gradient:#ffff55:#ffaa00><text></gradient>"
      low: "<gradient:#ff5555:#aa0000><text></gradient>"
    # Delay (in ticks) between bar update
    tick_interval: 20

  # Ram command format configuration
  ram:
    # If you like the original Purpur output, use this single following line:
    # - "<green>Ram Usage: <used>/<xmx> (<percent>)"
    output:
      - ""
      - "<color:#eb6ae8>Ram Usage"
      - ""
      - "<bar> <green><used>/<xmx> (<percent>)"
      - ""
    # If your custom characters are too wide, you can reduce this
    length: 80
    # Characters used to format the bar
    chars:
      bar: "|"
      start: "┨"
      end: "┠"
    # Hex colors used in the progressbar
    color:
      used: "#f099ee"
      unused: "#ababab"
      border: "#4a4a4a"

#
# Feedback messages when using commands
# These configurations only support Adventure's MiniMessage
# Learn more: https://docs.advntr.dev/minimessage/format.html
#
messages:
  no_permission: "<red>You have no permission to run this command"
  not_found: "<red>Command not found"
  not_player: "<red>This command can only be used by a player"
  failed_reload: "<red>Failed to load configuration!"
  successful_reload: "<green>Configuration reloaded!"
