main:
  rambar:
    title: "<gray>Ram<yellow>:</yellow> <used>/<xmx> (<percent>)"
    progress_overlay: "NOTCHED_20"
    progress_color:
      good: "GREEN"
      medium: "YELLOW"
      low: "RED"
    text_color:
      good: "<gradient:#55ff55:#00aa00><text></gradient>"
      medium: "<gradient:#ffff55:#ffaa00><text></gradient>"
      low: "<gradient:#ff5555:#aa0000><text></gradient>"
    tick_interval: 20
  tpsbar:
    title: "<gray>TPS<yellow>:</yellow> <tps> MSPT<yellow>:</yellow> <mspt> Ping<yellow>:</yellow> <ping>ms"
    progress_overlay: "NOTCHED_20"
    progress_fill_mode: "MSPT"
    progress_color:
      good: "GREEN"
      medium: "YELLOW"
      low: "RED"
    text_color:
      good: "<gradient:#55ff55:#00aa00><text></gradient>"
      medium: "<gradient:#ffff55:#ffaa00><text></gradient>"
      low: "<gradient:#ff5555:#aa0000><text></gradient>"
    tick_interval: 20